#if !LIVESHARP_DISABLE

// Use this attribute to designate which types and methods will be available for runtime code update

[assembly: LiveSharpInject("*")]

// Uncomment the following line if you want to provide a custom entry point for LiveSharp runtime
//[assembly: LiveSharpStart(typeof(Program), nameof(Program.Main), typeof(string[]))]

// Disable style warnings
// ReSharper disable once CheckNamespace
// <auto-generated/>
namespace BlazorIonic.Data
{
    class LiveSharpDashboard : ILiveSharpDashboard
    {
        // This method will be run during the start of your application and every time you update it
        public void Configure(ILiveSharpRuntime app)
        {
            //app.Config.SetValue("disableBlazorCSS", "false");
            app.UseDefaultBlazorHandler();
        }

        public void Run(ILiveSharpRuntime app)
        {
            // Use this method to execute any code in runtime
            // Every time you update this method LiveSharp will invoke it
        }
    }

    internal interface ILiveSharpDashboard
    {
    }
}
#endif